//go:build ignore

// Section 2, Topic 11: Constants — const keyword and untyped constants
//
// Constants in Go are declared with `const`. They must be computable at
// compile time (no function calls, no runtime values).
//
// Go has a unique feature: "untyped constants" — constants without an explicit
// type that have much higher precision and flexibility than typed values.
//


















































































































}	// Go constants have no address — you cannot take &Pi.	// Rust also has `static` for constants with an address in memory.	//	// Rust: const PI: f64 = 3.14;    (always typed, must annotate)	// Go:   const Pi float64 = 3.14  (typed, fixed)	// Go:   const Pi = 3.14   (untyped, flexible)	// ─────────────────────────────────────────────	// 8. Comparison: Go const vs Rust const	// ─────────────────────────────────────────────	fmt.Printf("Pi=%f, App=%s v%d, Debug=%t\n", Pi, AppName, AppVersion, Debug)	fmt.Println("\n-- Package-level constants --")	// ─────────────────────────────────────────────	// 7. Package-level constants	// ─────────────────────────────────────────────	// const c = 20 // ERROR: c already declared	// c++          // ERROR: cannot assign to c	// c = 20       // ERROR: cannot assign to c	const c = 10	// ─────────────────────────────────────────────	// 6. Constants are immutable	// ─────────────────────────────────────────────	fmt.Printf("MaxInt64 = %d\n", maxInt)	const maxInt = math.MaxInt64	// Constant expressions using built-in functions:	// NOT pointers, slices, maps, structs, arrays, channels, functions	// Basic types only: bool, string, int, float, complex, rune	// ─────────────────────────────────────────────	// 5. What CAN be a constant	// ─────────────────────────────────────────────	fmt.Printf("\nlen(\"hello\") = %d (constant)\n", strLen)	const strLen = len("hello") // ✓ compile-time computable	// But len of a string literal IS constant:	// const s = len([]int{1,2,3})  // ERROR: not a constant expression	// const now = time.Now()  // ERROR: time.Now() is not constant	// ─────────────────────────────────────────────	// 4. Constants must be compile-time computable	// ─────────────────────────────────────────────	fmt.Printf("huge as float64: %e\n", float64(huge))	// But you can use it in float expressions:	// var h int = huge  // ERROR: constant 1267650600228229401496703205376 overflows int	// You can't assign `huge` directly to a variable:	fmt.Println("huge >> 98 =", small)	const small = huge >> 98 // 1 << 2 = 4	// But it can still be used in expressions:	const huge = 1 << 100 // This would overflow any integer type	// Untyped constants have at least 256 bits of precision!	fmt.Println("\n-- Untyped constant precision --")	// ─────────────────────────────────────────────	// 3. Untyped constant precision	// ─────────────────────────────────────────────	fmt.Printf("typed int 42: int=%d\n", i)	var i int = y           // ✓ same type	// var f float64 = y    // ERROR: cannot use y (type int) as float64	const y int = 42	// Typed constant (fixed — behaves like a variable of that type)	fmt.Printf("untyped 42: int8=%d, float64=%f\n", i8, f64)	var f64 float64 = x    // ✓ 42 converts to float64	var i8 int8 = x       // ✓ 42 fits in int8	const x = 42	// Untyped constant (flexible — can be used as any compatible type)	fmt.Println("\n-- Typed vs untyped --")	// ─────────────────────────────────────────────	// 2. Typed vs untyped constants	// ─────────────────────────────────────────────	fmt.Printf("maxRetries=%d, pi=%.5f\n", maxRetries, pi)	fmt.Println(greeting)	const pi = 3.14159	const maxRetries = 3	const greeting = "Hello, Go!"	// ─────────────────────────────────────────────	// 1. Basic constant declaration	// ─────────────────────────────────────────────	fmt.Println()	fmt.Println("=== Constants ===")func main() {)	Debug      = false	AppVersion = 1	AppName    = "learn_go"const (// Factored (grouped) constantsconst Pi = 3.14159265358979323846// ─────────────────────────────────────────────// Package-level constants// ─────────────────────────────────────────────)	"math"	"fmt"import (package main// Run: go run examples/s02_constants.go//// GOTCHA: Untyped numeric constants have arbitrary precision (not limited to 64 bits).// GOTCHA: Constants cannot be pointers, slices, maps, or structs (only basic types).// GOTCHA: Constants cannot be declared with `:=`.