package examples
//go:build ignore














































































































}	// Go has no `let` — variables are declared with `var` or `:=`.	// Go has no `mut` keyword — all variables are mutable.	//	// Python: name = "Python"     (type inferred, mutable, no declaration needed)	// Rust:   let name = "Rust";  (type inferred, immutable by default)	// Go:     name := "Go"        (type inferred, mutable by default)	// ─────────────────────────────────────────────	// 8. Comparison: Go := vs Rust let vs Python =	// ─────────────────────────────────────────────	fmt.Printf("int32(42) → %T, float32(3.14) → %T\n", n32, f32)	f32 := float32(3.14)	n32 := int32(42)	// To get a specific type, use explicit conversion:	fmt.Printf("42 → %T, 3.14 → %T, 1+2i → %T\n", n, f, c)	fmt.Printf("\n-- Inferred types --\n")	c := 1 + 2i    // complex128	f := 3.14      // float64 (not float32)	n := 42        // int (not int32 or int64)	// ─────────────────────────────────────────────	// 7. Type of numeric literals	// ─────────────────────────────────────────────	// You must use `var` at package level.	//   name := "Go"  // syntax error: non-declaration statement outside function body	// At the top of the file, this would be a syntax error:	// ─────────────────────────────────────────────	// 6. GOTCHA: := cannot be used at package level	// ─────────────────────────────────────────────	fmt.Println("After assign:", msg) // "modified"	}		msg = "modified" // assigns to outer `msg`	if true {	// To modify the OUTER variable, use = not :=	fmt.Println("After if:", msg) // still "outer" — the inner `msg` is gone	}		fmt.Println("Inside if:", msg)		msg := "inner" // NEW variable in inner scope (shadow!)	if true {	fmt.Println("Before if:", msg)	fmt.Println("\n-- Shadowing --")	msg := "outer"	// ─────────────────────────────────────────────	// 5. GOTCHA: Shadowing with :=	// ─────────────────────────────────────────────	// val2, err := anotherFunction()  // err is reassigned, val2 is new	// val, err := someFunction()  // first call	// This is commonly used with error returns:	fmt.Printf("a=%d, b=%d\n", a, b)	a, b := 2, 3 // `a` is reassigned, `b` is newly declared	a := 1	// The existing variables are simply reassigned.	// If at least ONE variable on the left is new, := is legal.	// ─────────────────────────────────────────────	// 4. SPECIAL CASE: := with at least one new variable	// ─────────────────────────────────────────────	fmt.Printf("count=%d\n", count)	// count := 30  // ERROR: no new variables on left side of :=	count = 20    // assigns (variable already exists)	count := 10   // declares and initializes	// ─────────────────────────────────────────────	// 3. := vs = (declaration vs assignment)	// ─────────────────────────────────────────────	fmt.Printf("%s: %.1f, passed=%t\n", firstName, score, passed)	firstName, score, passed := "Alice", 95.5, true	// Mixed types:	fmt.Printf("x=%d, y=%d, z=%d\n", x, y, z)	x, y, z := 1, 2, 3	// ─────────────────────────────────────────────	// 2. Multiple variables	// ─────────────────────────────────────────────	fmt.Printf("name=%s, age=%d, pi=%.2f, awesome=%t\n", name, age, pi, isAwesome)	isAwesome := true   // inferred as bool	pi := 3.14159      // inferred as float64	age := 10          // inferred as int	name := "Gopher"  // inferred as string	// ─────────────────────────────────────────────	// 1. Basic usage	// ─────────────────────────────────────────────	fmt.Println()	fmt.Println("=== Short Variable Declaration (:=) ===")func main() {import "fmt"package main// Run: go run examples/s02_short_declaration.go//// GOTCHA: `:=` in an inner scope creates a NEW variable (shadow), not reassign.//         on the left side — the others can be existing variables (re-assignment).// GOTCHA: `:=` with multiple variables only requires at least ONE new variable// GOTCHA: `:=` can ONLY be used inside functions, NOT at package level.//// It is the most common way to declare variables inside functions.// The `:=` operator declares AND initializes a variable with type inference.//// Section 2, Topic 8: Short variable declaration (:=)